/**
 * 下载首尔区域 z10-z13 的高德瓦片并转换为 base64 内联数据
 * 生成 src/data/tiles/bundledTiles.ts
 *
 * 使用高德瓦片源因为 CARTO CDN 在国内无法访问。
 * 高德瓦片使用 Web Mercator 投影，瓦片坐标与 OSM/CARTO 一致。
 */

import * as fs from 'fs'
import * as path from 'path'

const SEOUL_BBOX = {
  north: 37.70,
  south: 37.39,
  east: 127.18,
  west: 126.70,
}

function lngToTileX(lng: number, z: number): number {
  return Math.floor((lng + 180) / 360 * Math.pow(2, z))
}

function latToTileY(lat: number, z: number): number {
  const latRad = lat * Math.PI / 180
  return Math.floor(
    (1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2 * Math.pow(2, z)
  )
}

function getTileRange(z: number): { xMin: number; xMax: number; yMin: number; yMax: number } {
  const xMin = lngToTileX(SEOUL_BBOX.west, z)
  const xMax = lngToTileX(SEOUL_BBOX.east, z)
  const yMin = latToTileY(SEOUL_BBOX.north, z)
  const yMax = latToTileY(SEOUL_BBOX.south, z)
  return { xMin, xMax, yMin, yMax }
}

async function downloadTile(
  z: number,
  x: number,
  y: number,
  retries = 3
): Promise<Buffer> {
  const url = `https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/${z}/${x}/${y}.png`
  for (let i = 0; i < retries; i++) {
    try {
      const resp = await fetch(url)
      if (resp.ok) return Buffer.from(await resp.arrayBuffer())
    } catch {
      if (i === retries - 1) throw new Error(`Failed to download tile ${z}/${x}/${y}`)
      await new Promise(r => setTimeout(r, 1000 * (i + 1)))
    }
  }
  throw new Error(`Failed to download tile ${z}/${x}/${y}`)
}

async function main() {
  const tiles: Record<string, string> = {}
  let total = 0
  let downloaded = 0
  let totalBytes = 0

  // Count total tiles
  for (let z = 10; z <= 13; z++) {
    const { xMin, xMax, yMin, yMax } = getTileRange(z)
    total += (xMax - xMin + 1) * (yMax - yMin + 1)
  }

  console.log(`Downloading ${total} tiles for Seoul (z10-z13)...`)

  for (let z = 10; z <= 13; z++) {
    const { xMin, xMax, yMin, yMax } = getTileRange(z)
    const count = (xMax - xMin + 1) * (yMax - yMin + 1)
    console.log(`  z${z}: x(${xMin}-${xMax}), y(${yMin}-${yMax}), ${count} tiles`)

    for (let x = xMin; x <= xMax; x++) {
      for (let y = yMin; y <= yMax; y++) {
        const key = `${z}/${x}/${y}`
        const buf = await downloadTile(z, x, y)
        const base64 = buf.toString('base64')
        tiles[key] = `data:image/png;base64,${base64}`
        totalBytes += buf.length
        downloaded++
        if (downloaded % 20 === 0 || downloaded === total) {
          console.log(`    ${downloaded}/${total} tiles (${(totalBytes / 1024 / 1024).toFixed(1)} MB)`)
        }
      }
    }
  }

  // Generate TypeScript file
  const entries = Object.entries(tiles)
    .map(([k, v]) => `  '${k}': '${v}'`)
    .join(',\n')

  const content = `// Auto-generated by scripts/download-tiles.ts
// Contains ${downloaded} tiles, ${(totalBytes / 1024 / 1024).toFixed(2)} MB original

export const bundledTiles: Record<string, string> = {
${entries}
}
`

  const outPath = path.join(process.cwd(), 'src', 'data', 'tiles', 'bundledTiles.ts')
  fs.writeFileSync(outPath, content, 'utf-8')

  const base64Size = Math.round(totalBytes * 1.33)
  console.log(`\nGenerated ${outPath}`)
  console.log(`Tiles: ${downloaded}`)
  console.log(`Original: ${(totalBytes / 1024 / 1024).toFixed(2)} MB`)
  console.log(`Base64: ${(base64Size / 1024 / 1024).toFixed(2)} MB`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
